import * as RNLocalize from 'react-native-localize';

export const getDeviceTimezone = () => RNLocalize.getTimeZone();

export const TIMEZONE_LIST = [
  { timezone: 'America/New_York', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'Asia/Kolkata', name: 'India Standard Time', country: 'India' },
  { timezone: 'Asia/Kabul', name: 'Afghanistan Time', country: 'Afghanistan' },
  { timezone: 'Europe/Tirane', name: 'Central European Standard Time', country: 'Albania' },
  { timezone: 'America/Los_Angeles', name: 'Pacific Standard Time', country: 'United States' },
  { timezone: 'America/Vancouver', name: 'Pacific Standard Time', country: 'Canada' },
  { timezone: 'Pacific/Honolulu', name: 'Hawaiian Standard Time', country: 'United States' },
  { timezone: 'Pacific/Johnston', name: 'Hawaiian Standard Time', country: 'United States' },
  { timezone: 'America/Toronto', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Chicago', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/Phoenix', name: 'US Mountain Standard Time', country: 'United States' },
  { timezone: 'America/Indianapolis', name: 'US Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Denver', name: 'Mountain Standard Time', country: 'United States' },
  { timezone: 'America/Detroit', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Montreal', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Edmonton', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Winnipeg', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'Africa/Algiers', name: 'Central European Time', country: 'Algeria' },
  { timezone: 'Pacific/Pago_Pago', name: 'Samoa Standard Time', country: 'American Samoa' },
  { timezone: 'Europe/Andorra', name: 'Central European Time', country: 'Andorra' },
  { timezone: 'Africa/Luanda', name: 'West Africa Time', country: 'Angola' },
  { timezone: 'Antarctica/Casey', name: 'Casey Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Davis', name: 'Davis Time', country: 'Antarctica' },
  { timezone: 'Antarctica/DumontDUrville', name: "Dumont-d'Urville Time", country: 'Antarctica' },
  { timezone: 'Antarctica/Mawson', name: 'Mawson Time', country: 'Antarctica' },
  { timezone: 'Antarctica/McMurdo', name: 'New Zealand Standard Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Palmer', name: ' Chile Summer Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Rothera', name: 'Argentina Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Syowa', name: 'Syowa Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Troll', name: 'Greenwich Mean Time', country: 'Antarctica' },
  { timezone: 'Antarctica/Vostok', name: 'Vostok Station Time', country: 'Antarctica' },
  { timezone: 'America/Antigua', name: 'Atlantic Standard Time', country: 'Antigua and Barbuda' },
  { timezone: 'America/Argentina/Buenos_Aires', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Catamarca', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Cordoba', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Jujuy', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/La_Rioja', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Mendoza', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Rio_Gallegos', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Salta', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/San_Juan', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/San_Luis', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Tucuman', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'America/Argentina/Ushuaia', name: 'Argentina Time', country: 'Argentina' },
  { timezone: 'Asia/Yerevan', name: 'Armenia Time', country: 'Armenia' },
  { timezone: 'America/Aruba', name: 'Atlantic Standard Time', country: 'Aruba' },
  { timezone: 'Antarctica/Macquarie', name: 'Australian Eastern Daylight Time', country: 'Australia' },
  { timezone: 'Australia/Adelaide', name: 'Australian Central Daylight Time', country: 'Australia' },
  { timezone: 'Australia/Brisbane', name: 'Australian Eastern Standard Time', country: 'Australia' },
  { timezone: 'Australia/Broken_Hill', name: 'Australian Central Daylight Time', country: 'Australia' },
  { timezone: 'Australia/Darwin', name: 'Australian Central Western Standard Time', country: 'Australia' },
  { timezone: 'Australia/Eucla', name: 'Australian Central Western Standard Time', country: 'Australia' },
  { timezone: 'Australia/Hobart', name: 'Australian Eastern Daylight Time', country: 'Australia' },
  { timezone: 'Australia/Lindeman', name: 'Australian Eastern Standard Time', country: 'Australia' },
  { timezone: 'Australia/Lord_Howe', name: 'Lord Howe Standard Time', country: 'Australia' },
  { timezone: 'Australia/Melbourne', name: 'Australian Eastern Daylight Time', country: 'Australia' },
  { timezone: 'Australia/Perth', name: 'Australian Western Standard Time', country: 'Australia' },
  { timezone: 'Australia/Sydney', name: 'Australian Eastern Daylight Time', country: 'Australia' },
  { timezone: 'Europe/Vienna', name: 'Central European Time', country: 'Austria' },
  { timezone: 'Asia/Baku', name: 'Azerbaijan Time', country: 'Azerbaijan' },
  { timezone: 'America/Nassau', name: 'Eastern Standard Time', country: 'Bahamas' },
  { timezone: 'Asia/Bahrain', name: 'Arabian Standard Time', country: 'Bahrain' },
  { timezone: 'Asia/Dhaka', name: 'Bangladesh Standard Time', country: 'Bangladesh' },
  { timezone: 'America/Barbados', name: 'Atlantic Standard Time', country: 'Barbados' },
  { timezone: 'Europe/Minsk', name: 'Moscow Standard Time', country: 'Belarus' },
  { timezone: 'Europe/Brussels', name: 'Central European Standard Time', country: 'Belgium' },
  { timezone: 'America/Belize', name: 'Central Standard Time', country: 'Belize' },
  { timezone: 'Africa/Porto-Novo', name: 'West Africa Standard Time', country: 'Benin' },
  { timezone: 'Atlantic/Bermuda', name: 'Atlantic Standard Time', country: 'Bermuda' },
  { timezone: 'Asia/Thimphu', name: 'Bhutan Time', country: 'Bhutan' },
  { timezone: 'America/La_Paz', name: 'Bolivia Time', country: 'Bolivia, Plurinational State of' },
  { timezone: 'America/Kralendijk', name: 'Atlantic Standard Time', country: 'Bonaire, Sint Eustatius and Saba' },
  { timezone: 'Europe/Sarajevo', name: 'Central European Time', country: 'Bosnia and Herzegovina' },
  { timezone: 'Africa/Gaborone', name: 'Central Africa Time', country: 'Botswana' },
  { timezone: 'America/Araguaina', name: 'Brasília Time', country: 'Brazil' },
  { timezone: 'America/Bahia', name: 'Brasília Time', country: 'Brazil' },
  { timezone: 'America/Belem', name: 'Brasília Time', country: 'Brazil' },
  { timezone: 'America/Boa_Vista', name: 'Amazon Standard Time', country: 'Brazil' },
  { timezone: 'America/Campo_Grande', name: 'Amazon Standard Time', country: 'Brazil' },
  { timezone: 'America/Cuiaba', name: 'Amazon Standard Time', country: 'Brazil' },
  { timezone: 'America/Eirunepe', name: 'Acre Standard Time', country: 'Brazil' },
  { timezone: 'America/Fortaleza', name: 'Brasilia Standard Time', country: 'Brazil' },
  { timezone: 'America/Maceio', name: 'Brasilia Standard Time', country: 'Brazil' },
  { timezone: 'America/Manaus', name: 'Amazon Standard Time', country: 'Brazil' },
  { timezone: 'America/Noronha', name: 'UTC-2', country: 'Brazil' },
  { timezone: 'America/Porto_Velho', name: 'Amazon Standard Time', country: 'Brazil' },
  { timezone: 'America/Recife', name: 'Brasilia Standard Time', country: 'Brazil' },
  { timezone: 'America/Rio_Branco', name: 'Acre Standard Time', country: 'Brazil' },
  { timezone: 'America/Santarem', name: 'Brasilia Standard Time', country: 'Brazil' },
  { timezone: 'America/Sao_Paulo', name: 'Brasilia Standard Time', country: 'Brazil' },
  { timezone: 'Indian/Chagos', name: 'Indian Chagos Time', country: 'British Indian Ocean Territory' },
  { timezone: 'Asia/Brunei', name: 'Brunei Darussalam Time', country: 'Brunei Darussalam' },
  { timezone: 'Europe/Sofia', name: 'Eastern European Standard Time', country: 'Bulgaria' },
  { timezone: 'Africa/Ouagadougou', name: 'Greenwich Mean Time', country: 'Burkina Faso' },
  { timezone: 'Africa/Bujumbura', name: 'Central Africa Time', country: 'Burundi' },
  { timezone: 'Asia/Phnom_Penh', name: 'Indochina Time', country: 'Cambodia' },
  { timezone: 'Africa/Douala', name: 'West Africa Standard Time', country: 'Cameroon' },
  { timezone: 'America/Atikokan', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Blanc-Sablon', name: 'Atlantic Standard Time', country: 'Canada' },
  { timezone: 'America/Cambridge_Bay', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Creston', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Dawson', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Dawson_Creek', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Fort_Nelson', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Glace_Bay', name: 'Atlantic Standard Time', country: 'Canada' },
  { timezone: 'America/Goose_Bay', name: 'Atlantic Standard Time', country: 'Canada' },
  { timezone: 'America/Halifax', name: 'Atlantic Standard Time', country: 'Canada' },
  { timezone: 'America/Inuvik', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Iqaluit', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Moncton', name: 'Atlantic Standard Time', country: 'Canada' },
  { timezone: 'America/Nipigon', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Pangnirtung', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Rainy_River', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'America/Rankin_Inlet', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'America/Regina', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'America/Resolute', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'America/St_Johns', name: 'Newfoundland Standard Time', country: 'Canada' },
  { timezone: 'America/Swift_Current', name: 'Central Standard Time', country: 'Canada' },
  { timezone: 'America/Thunder_Bay', name: 'Eastern Standard Time', country: 'Canada' },
  { timezone: 'America/Whitehorse', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'America/Yellowknife', name: 'Mountain Standard Time', country: 'Canada' },
  { timezone: 'Atlantic/Cape_Verde', name: 'Cape Verde Standard Time', country: 'Cape Verde' },
  { timezone: 'America/Cayman', name: 'Eastern Standard Time', country: 'Cayman Islands' },
  { timezone: 'Africa/Bangui', name: 'West Africa Standard Time', country: 'Central African Republic' },
  { timezone: 'Africa/Ndjamena', name: 'West Africa Standard Time', country: 'Chad' },
  { timezone: 'America/Punta_Arenas', name: 'Chile Summer Time', country: 'Chile' },
  { timezone: 'America/Santiago', name: 'Chile Summer Time', country: 'Chile' },
  { timezone: 'Pacific/Easter', name: 'Easter Island Summer Time', country: 'Chile' },
  { timezone: 'Asia/Shanghai', name: 'China Standard Time', country: 'China' },
  { timezone: 'Asia/Urumqi', name: 'China Standard Time', country: 'China' },
  { timezone: 'Indian/Christmas', name: 'Christmas Island Time', country: 'Christmas Island' },
  { timezone: 'Indian/Cocos', name: 'Cocos Islands Time', country: 'Cocos (Keeling) Islands' },
  { timezone: 'America/Bogota', name: 'Colombia Standard Time', country: 'America/Bogota' },
  { timezone: 'Indian/Comoro', name: 'East Africa Time', country: 'Comoros' },
  { timezone: 'Africa/Brazzaville', name: 'West Africa Standard Time', country: 'Congo' },
  { timezone: 'Africa/Kinshasa', name: 'West Africa Standard Time', country: 'Congo, the Democratic Republic of the' },
  { timezone: 'Africa/Lubumbashi', name: 'Central Africa Time', country: 'Congo, the Democratic Republic of the' },
  { timezone: 'Pacific/Rarotonga', name: 'Cook Islands Standard Time', country: 'Cook Islands' },
  { timezone: 'America/Costa_Rica', name: 'Central Standard Time', country: 'Costa Rica' },
  { timezone: 'Europe/Zagreb', name: 'Central European Standard Time', country: 'Croatia' },
  { timezone: 'America/Havana', name: 'Cuba Standard Time', country: 'Cuba' },
  { timezone: 'America/Curacao', name: 'Atlantic Standard Time', country: 'Curaçao' },
  { timezone: 'Asia/Famagusta', name: 'Eastern European Time', country: 'Cyprus' },
  { timezone: 'Asia/Nicosia', name: 'Eastern European Time', country: 'Cyprus' },
  { timezone: 'Europe/Prague', name: 'Central European Standard Time', country: 'Czech Republic' },
  { timezone: 'Africa/Abidjan', name: 'Greenwich Mean Time', country: "Côte d'Ivoire" },
  { timezone: 'Europe/Copenhagen', name: 'Central European Standard Time', country: 'Denmark' },
  { timezone: 'Africa/Djibouti', name: 'East Africa Time', country: 'Djibouti' },
  { timezone: 'America/Dominica', name: 'Atlantic Standard Time', country: 'Dominica' },
  { timezone: 'America/Santo_Domingo', name: 'Atlantic Standard Time', country: 'Dominican Republic' },
  { timezone: 'America/Guayaquil', name: 'Ecuador Time', country: 'Ecuador' },
  { timezone: 'Pacific/Galapagos', name: 'Galapagos Time', country: 'Ecuador' },
  { timezone: 'Africa/Cairo', name: 'Eastern European Time', country: 'Africa/Cairo' },
  { timezone: 'America/El_Salvador', name: 'Central Standard Time', country: 'El Salvador' },
  { timezone: 'Africa/Malabo', name: 'West Africa Time', country: 'Equatorial Guinea' },
  { timezone: 'Africa/Asmara', name: 'East Africa Time', country: 'Eritrea' },
  { timezone: 'Europe/Tallinn', name: 'Eastern European Time', country: 'Estonia' },
  { timezone: 'Africa/Addis_Ababa', name: 'East Africa Time', country: 'Ethiopia' },
  { timezone: 'Atlantic/Stanley', name: 'Falkland Islands Time', country: 'Falkland Islands (Malvinas)' },
  { timezone: 'Atlantic/Faroe', name: 'Western European Time', country: 'Faroe Islands' },
  { timezone: 'Pacific/Fiji', name: 'Fiji Time', country: 'Fiji' },
  { timezone: 'Europe/Helsinki', name: 'Eastern European Time', country: 'Finland' },
  { timezone: 'Europe/Paris', name: 'Central European Time', country: 'France' },
  { timezone: 'America/Cayenne', name: 'French Guiana Time', country: 'French Guiana' },
  { timezone: 'Pacific/Gambier', name: 'Gambier Time', country: 'French Polynesia' },
  { timezone: 'Pacific/Marquesas', name: 'Central Standard Time', country: 'French Polynesia' },
  { timezone: 'Pacific/Tahiti', name: 'Tahiti Time', country: 'Pacific/Tahiti' },
  { timezone: 'Indian/Kerguelen', name: 'French Southern and Antarctic Time', country: 'French Southern Territories' },
  { timezone: 'Africa/Libreville', name: 'West Africa Time', country: 'Gabon' },
  { timezone: 'Africa/Banjul', name: 'Greenwich Mean Time', country: 'Gambia' },
  { timezone: 'Asia/Tbilisi', name: ' Georgia Standard Time', country: 'Georgia' },
  { timezone: 'Europe/Berlin', name: 'Central European Standard Time', country: 'Germany' },
  { timezone: 'Europe/Busingen', name: 'Central European Standard Time', country: 'Germany' },
  { timezone: 'Africa/Accra', name: 'Greenwich Mean Time', country: 'Ghana' },
  { timezone: 'Europe/Gibraltar', name: 'Central European Standard Time', country: 'Gibraltar' },
  { timezone: 'Europe/Athens', name: 'Eastern European Standard Time', country: 'Greece' },
  { timezone: 'America/Danmarkshavn', name: 'Greenwich Mean Time', country: 'Greenland' },
  { timezone: 'America/Nuuk', name: 'West Greenland Standard Time', country: 'Greenland' },
  { timezone: 'America/Scoresbysund', name: 'East Greenland Standard Time', country: 'Greenland' },
  { timezone: 'America/Thule', name: 'Atlantic Standard Time', country: 'Greenland' },
  { timezone: 'America/Grenada', name: 'Atlantic Standard Time', country: 'Grenada' },
  { timezone: 'America/Guadeloupe', name: 'Atlantic Standard Time', country: 'Guadeloupe' },
  { timezone: 'Pacific/Guam', name: 'Chamorro Standard Time', country: 'Guam' },
  { timezone: 'America/Guatemala', name: 'Central Standard Time', country: 'Guatemala' },
  { timezone: 'Europe/Guernsey', name: 'Greenwich Mean Time', country: 'Europe/Guernsey' },
  { timezone: 'Africa/Conakry', name: 'Greenwich Mean Time', country: 'Guinea' },
  { timezone: 'Africa/Bissau', name: 'Greenwich Mean Time', country: 'Guinea-Bissau' },
  { timezone: 'America/Guyana', name: 'Guyana Time', country: 'Guyana' },
  { timezone: 'America/Port-au-Prince', name: 'Eastern Standard Time', country: 'Haiti' },
  { timezone: 'Europe/Vatican', name: 'Central European Standard Time', country: 'Holy See (Vatican City State)' },
  { timezone: 'America/Tegucigalpa', name: 'Central Standard Time', country: 'Honduras' },
  { timezone: 'Asia/Hong_Kong', name: 'Hong Kong Standard Time', country: 'Hong Kong' },
  { timezone: 'Europe/Budapest', name: 'Central European Standard Time', country: 'Hungary' },
  { timezone: 'Atlantic/Reykjavik', name: 'Greenwich Mean Time', country: 'Iceland' },
  { timezone: 'Asia/Jakarta', name: 'Western Indonesia Time', country: 'Indonesia' },
  { timezone: 'Asia/Jayapura', name: 'Eastern Indonesia Time', country: 'Indonesia' },
  { timezone: 'Asia/Makassar', name: 'Central Indonesia Time', country: 'Indonesia' },
  { timezone: 'Asia/Pontianak', name: 'Western Indonesian Time', country: 'Indonesia' },
  { timezone: 'Asia/Tehran', name: 'Iran Standard Time', country: 'Iran, Islamic Republic of' },
  { timezone: 'Asia/Baghdad', name: 'Arabian Standard Time', country: 'Iraq' },
  { timezone: 'Europe/Dublin', name: 'Greenwich Mean Time', country: 'Ireland' },
  { timezone: 'Europe/Isle_of_Man', name: 'Greenwich Mean Time', country: 'Isle of Man' },
  { timezone: 'Asia/Jerusalem', name: 'Israel Standard Time', country: 'Israel' },
  { timezone: 'Europe/Rome', name: 'Central European Standard Time', country: 'Italy' },
  { timezone: 'America/Jamaica', name: 'Eastern Standard Time', country: 'Jamaica' },
  { timezone: 'Asia/Tokyo', name: 'Japan Standard Time', country: 'Japan' },
  { timezone: 'Europe/Jersey', name: 'Greenwich Mean Time', country: 'Jersey' },
  { timezone: 'Asia/Amman', name: 'Eastern European Standard Time', country: 'Jordan' },
  { timezone: 'Asia/Almaty', name: 'East Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Aqtau', name: 'West Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Aqtobe', name: 'West Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Atyrau', name: 'West Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Oral', name: 'Oral Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Qostanay', name: 'West Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Asia/Qyzylorda', name: 'West Kazakhstan Time', country: 'Kazakhstan' },
  { timezone: 'Africa/Nairobi', name: 'East Africa Time', country: 'Kenya' },
  { timezone: 'Pacific/Enderbury', name: 'Phoenix Islands Time', country: 'Kiribati' },
  { timezone: 'Pacific/Kiritimati', name: 'Line Islands Time', country: 'Kiribati' },
  { timezone: 'Pacific/Tarawa', name: 'Gilbert Islands Time', country: 'Kiribati' },
  { timezone: 'Asia/Pyongyang', name: 'Korean Standard Time', country: "Korea, Democratic People's Republic of" },
  { timezone: 'Asia/Seoul', name: 'Korean Standard Time', country: 'Korea, Republic of' },
  { timezone: 'Asia/Kuwait', name: 'Arabian Standard Time', country: 'Kuwait' },
  { timezone: 'Asia/Bishkek', name: 'Kyrgyzstan Time', country: 'Kyrgyzstan' },
  { timezone: 'Asia/Vientiane', name: 'Indochina Time', country: "Lao People's Democratic Republic" },
  { timezone: 'Europe/Riga', name: 'Eastern European Standard Time', country: 'Latvia' },
  { timezone: 'Asia/Beirut', name: 'Eastern European Standard Time', country: 'Lebanon' },
  { timezone: 'Africa/Maseru', name: 'South Africa Standard Time', country: 'Lesotho' },
  { timezone: 'Africa/Monrovia', name: 'Greenwich Mean Time', country: 'Liberia' },
  { timezone: 'Africa/Tripoli', name: 'Eastern European Standard Time', country: 'Libya' },
  { timezone: 'Europe/Vaduz', name: 'Central European Standard Time', country: 'Liechtenstein' },
  { timezone: 'Europe/Vilnius', name: 'Eastern European Standard Time', country: 'Lithuania' },
  { timezone: 'Europe/Luxembourg', name: 'Central European Standard Time', country: 'Luxembourg' },
  { timezone: 'Asia/Macau', name: 'China Standard Time', country: 'Macao' },
  {
    timezone: 'Europe/Skopje',
    name: 'Central European Standard Time',
    country: 'Macedonia, the Former Yugoslav Republic of',
  },
  { timezone: 'Indian/Antananarivo', name: 'East Africa Time', country: 'Madagascar' },
  { timezone: 'Africa/Blantyre', name: 'Central Africa Time', country: 'Malawi' },
  { timezone: 'Asia/Kuala_Lumpur', name: 'Malaysia Time', country: 'Malaysia' },
  { timezone: 'Asia/Kuching', name: 'Malaysia Time', country: 'Malaysia' },
  { timezone: 'Indian/Maldives', name: 'Maldives Time', country: 'Maldives' },
  { timezone: 'Africa/Bamako', name: 'Greenwich Mean Time', country: 'Mali' },
  { timezone: 'Europe/Malta', name: 'Central European Standard Time', country: 'Malta' },
  { timezone: 'Pacific/Kwajalein', name: 'Marshall Islands Time', country: 'Marshall Islands' },
  { timezone: 'Pacific/Majuro', name: 'Marshall Islands Time', country: 'Marshall Islands' },
  { timezone: 'America/Martinique', name: 'Atlantic Standard Time', country: 'Martinique' },
  { timezone: 'Africa/Nouakchott', name: 'Greenwich Mean Time', country: 'Mauritania' },
  { timezone: 'Indian/Mauritius', name: 'Mauritius Standard Time', country: 'Mauritius' },
  { timezone: 'Indian/Mayotte', name: 'East Africa Time', country: 'Mayotte' },
  { timezone: 'America/Bahia_Banderas', name: 'Central Standard Time', country: 'Mexico' },
  { timezone: 'America/Cancun', name: 'Eastern Standard Time', country: 'Mexico' },
  { timezone: 'America/Chihuahua', name: 'Mexican Pacific Standard Time', country: 'Mexico' },
  { timezone: 'America/Hermosillo', name: 'Mexican Pacific Standard Time', country: 'Mexico' },
  { timezone: 'America/Matamoros', name: 'Central Standard Time', country: 'Mexico' },
  { timezone: 'America/Mazatlan', name: 'Mexican Pacific Standard Time', country: 'Mexico' },
  { timezone: 'America/Merida', name: 'Central Standard Time', country: 'Mexico' },
  { timezone: 'America/Mexico_City', name: 'Central Standard Time', country: 'Mexico' },
  { timezone: 'America/Monterrey', name: 'Central Standard Time', country: 'Mexico' },
  { timezone: 'America/Ojinaga', name: 'Mountain Standard Time', country: 'Mexico' },
  { timezone: 'America/Tijuana', name: 'Pacific Standard Time', country: 'Mexico' },
  { timezone: 'Pacific/Chuuk', name: 'Chuuk Time', country: 'Micronesia, Federated States of' },
  { timezone: 'Pacific/Kosrae', name: 'Kosrae Time', country: 'Micronesia, Federated States of' },
  { timezone: 'Pacific/Pohnpei', name: 'Ponape Time', country: 'Micronesia, Federated States of' },
  { timezone: 'Europe/Chisinau', name: 'Eastern European Standard Time', country: 'Moldova, Republic of' },
  { timezone: 'Europe/Monaco', name: 'Central European Standard Time', country: 'Monaco' },
  { timezone: 'Asia/Choibalsan', name: 'Choibalsan Summer Time', country: 'Mongolia' },
  { timezone: 'Asia/Hovd', name: 'Hovd Standard Time', country: 'Mongolia' },
  { timezone: 'Asia/Ulaanbaatar', name: 'Ulaanbaatar Standard Time', country: 'Mongolia' },
  { timezone: 'Europe/Podgorica', name: 'Central European Standard Time', country: 'Montenegro' },
  { timezone: 'America/Montserrat', name: 'Atlantic Standard Time', country: 'Montserrat' },
  { timezone: 'Africa/Casablanca', name: 'Western European Summer Time', country: 'Morocco' },
  { timezone: 'Africa/Maputo', name: 'Central Africa Time', country: 'Mozambique' },
  { timezone: 'Asia/Yangon', name: 'Myanmar Time', country: 'Myanmar' },
  { timezone: 'Africa/Windhoek', name: 'Central Africa Time', country: 'Namibia' },
  { timezone: 'Pacific/Nauru', name: 'Nauru Time', country: 'Nauru' },
  { timezone: 'Asia/Kathmandu', name: 'Nepal Time', country: 'Nepal' },
  { timezone: 'Europe/Amsterdam', name: 'Central European Time', country: 'Netherlands' },
  { timezone: 'Pacific/Noumea', name: 'New Caledonia Standard Time', country: 'New Caledonia' },
  { timezone: 'Pacific/Auckland', name: 'New Zealand Daylight Time', country: 'New Zealand' },
  { timezone: 'Pacific/Chatham', name: 'Eastern Standard Time', country: 'New Zealand' },
  { timezone: 'America/Managua', name: 'Central Standard Time', country: 'Nicaragua' },
  { timezone: 'Africa/Niamey', name: 'West Africa Standard Time', country: 'Niger' },
  { timezone: 'Africa/Lagos', name: 'West Africa Standard Time', country: 'Nigeria' },
  { timezone: 'Pacific/Niue', name: 'Niue Time', country: 'Niue' },
  { timezone: 'Pacific/Norfolk', name: 'Eastern Standard Time', country: 'Norfolk Island' },
  { timezone: 'Pacific/Saipan', name: 'Chamorro Standard Time', country: 'Northern Mariana Islands' },
  { timezone: 'Europe/Oslo', name: 'Central European Standard Time', country: 'Norway' },
  { timezone: 'Asia/Muscat', name: 'Gulf Standard Time', country: 'Oman' },
  { timezone: 'Asia/Karachi', name: 'Pakistan Standard Time', country: 'Pakistan' },
  { timezone: 'Pacific/Palau', name: 'Palau Time', country: 'Palau' },
  { timezone: 'Asia/Gaza', name: 'Eastern European Standard Time', country: 'Palestine, State of' },
  { timezone: 'Asia/Hebron', name: 'Eastern European Standard Time', country: 'Palestine, State of' },
  { timezone: 'America/Panama', name: 'Eastern Standard Time', country: 'Panama' },
  { timezone: 'Pacific/Bougainville', name: 'British Summer Time', country: 'Papua New Guinea' },
  { timezone: 'Pacific/Port_Moresby', name: 'Papua New Guinea Time', country: 'Papua New Guinea' },
  { timezone: 'America/Asuncion', name: 'Paraguay Summer Time', country: 'America/Asuncion' },
  { timezone: 'America/Lima', name: 'Peru Standard Time', country: 'Peru' },
  { timezone: 'Asia/Manila', name: 'Philippine Standard Time', country: 'Philippines' },
  { timezone: 'Pacific/Pitcairn', name: 'Pitcairn Time', country: 'Pitcairn' },
  { timezone: 'Europe/Warsaw', name: 'Central European Standard Time', country: 'Poland' },
  { timezone: 'Atlantic/Azores', name: 'Azores Standard Time', country: 'Portugal' },
  { timezone: 'Atlantic/Madeira', name: 'Western European Standard Time', country: 'Portugal' },
  { timezone: 'Europe/Lisbon', name: 'Western European Standard Time', country: 'Portugal' },
  { timezone: 'America/Puerto_Rico', name: 'Atlantic Standard Time', country: 'Puerto Rico' },
  { timezone: 'Asia/Qatar', name: 'Arabian Standard Time', country: 'Qatar' },
  { timezone: 'Europe/Bucharest', name: 'Eastern European Standard Time', country: 'Romania' },
  { timezone: 'Asia/Anadyr', name: 'Anadyr Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Barnaul', name: 'Krasnoyarsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Chita', name: 'Yakutsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Irkutsk', name: 'Irkutsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Kamchatka', name: 'Petropavlovsk-Kamchatski Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Khandyga', name: 'Yakutsk Time', country: 'Russian Federation' },
  { timezone: 'Asia/Krasnoyarsk', name: 'Krasnoyarsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Magadan', name: 'Magadan Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Novokuznetsk', name: 'Krasnoyarsk Time', country: 'Russian Federation' },
  { timezone: 'Asia/Novosibirsk', name: 'Novosibirsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Omsk', name: 'Omsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Sakhalin', name: 'Magadan Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Tomsk', name: 'Novosibirsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Ust-Nera', name: 'Vladivostok Time', country: 'Russian Federation' },
  { timezone: 'Asia/Vladivostok', name: 'Vladivostok Time', country: 'Russian Federation' },
  { timezone: 'Asia/Yakutsk', name: 'Yakutsk Standard Time', country: 'Russian Federation' },
  { timezone: 'Asia/Yekaterinburg', name: 'Yekaterinburg Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Astrakhan', name: 'Samara Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Kaliningrad', name: 'Eastern European Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Kirov', name: 'Moscow Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Moscow', name: 'Moscow Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Samara', name: 'Samara Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Saratov', name: 'Moscow Daylight Time', country: 'Russian Federation' },
  { timezone: 'Europe/Ulyanovsk', name: 'Samara Standard Time', country: 'Russian Federation' },
  { timezone: 'Europe/Volgograd', name: 'Volgograd Standard Time', country: 'Russian Federation' },
  { timezone: 'Africa/Kigali', name: 'Central Africa Time', country: 'Rwanda' },
  { timezone: 'Indian/Reunion', name: 'Réunion Time', country: 'Réunion' },
  { timezone: 'America/St_Barthelemy', name: 'Atlantic Standard Time', country: 'Saint Barthélemy' },
  {
    timezone: 'Atlantic/St_Helena',
    name: 'Greenwich Mean Time',
    country: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  { timezone: 'America/St_Kitts', name: 'Atlantic Standard Time', country: 'Saint Kitts and Nevis' },
  { timezone: 'America/St_Lucia', name: 'Atlantic Standard Time', country: 'Saint Lucia' },
  { timezone: 'America/Marigot', name: 'Atlantic Standard Time', country: 'Saint Martin (French part)' },
  { timezone: 'America/Miquelon', name: 'St Pierre & Miquelon Standard Time', country: 'Saint Pierre and Miquelon' },
  { timezone: 'America/St_Vincent', name: 'Atlantic Standard Time', country: 'Saint Vincent and the Grenadines' },
  { timezone: 'Pacific/Apia', name: 'Apia Daylight Time', country: 'Samoa' },
  { timezone: 'Europe/San_Marino', name: 'Central European Standard Time', country: 'San Marino' },
  { timezone: 'Africa/Sao_Tome', name: 'Greenwich Mean Time', country: 'Sao Tome and Principe' },
  { timezone: 'Asia/Riyadh', name: 'Arabian Standard Time', country: 'Saudi Arabia' },
  { timezone: 'Africa/Dakar', name: 'Greenwich Mean Time', country: 'Senegal' },
  { timezone: 'Europe/Belgrade', name: 'Central European Standard Time', country: 'Serbia' },
  { timezone: 'Indian/Mahe', name: 'Seychelles Time', country: 'Seychelles' },
  { timezone: 'Africa/Freetown', name: 'Greenwich Mean Time', country: 'Sierra Leone' },
  { timezone: 'Asia/Singapore', name: 'Singapore Standard Time', country: 'Singapore' },
  { timezone: 'America/Lower_Princes', name: 'Atlantic Standard Time', country: 'Sint Maarten (Dutch part)' },
  { timezone: 'Europe/Bratislava', name: 'Central European Standard Time', country: 'Slovakia' },
  { timezone: 'Europe/Ljubljana', name: 'Central European Standard Time', country: 'Slovenia' },
  { timezone: 'Pacific/Guadalcanal', name: 'Solomon Islands Time', country: 'Solomon Islands' },
  { timezone: 'Africa/Mogadishu', name: 'East Africa Time', country: 'Somalia' },
  { timezone: 'Africa/Johannesburg', name: 'South Africa Standard Time', country: 'South Africa' },
  {
    timezone: 'Atlantic/South_Georgia	',
    name: 'South Georgia Time',
    country: 'South Georgia and the South Sandwich Islands',
  },
  { timezone: 'Africa/Juba', name: 'East Africa Time', country: 'South Sudan' },
  { timezone: 'Africa/Ceuta', name: 'Central European Standard Time', country: 'Spain' },
  { timezone: 'Atlantic/Canary', name: 'Western European Standard Time', country: 'Spain' },
  { timezone: 'Europe/Madrid', name: 'Central European Standard Time', country: 'Spain' },
  { timezone: 'Asia/Colombo', name: 'India Standard Time', country: 'Sri Lanka' },
  { timezone: 'Africa/Khartoum', name: 'Central Africa Time', country: 'Sudan' },
  { timezone: 'America/Paramaribo', name: 'Suriname Time', country: 'Suriname' },
  { timezone: 'Arctic/Longyearbyen', name: 'Central European Standard Time', country: 'Svalbard and Jan Mayen' },
  { timezone: 'Africa/Mbabane', name: 'South Africa Standard Time', country: 'Swaziland' },
  { timezone: 'Europe/Stockholm', name: 'Central European Standard Time', country: 'Sweden' },
  { timezone: 'Europe/Zurich', name: 'Central European Standard Time', country: 'Switzerland' },
  { timezone: 'Asia/Damascus', name: 'Eastern European Standard Time', country: 'Syrian Arab Republic' },
  { timezone: 'Asia/Taipei', name: 'Taipei Standard Time', country: 'Taiwan, Province of China' },
  { timezone: 'Asia/Dushanbe', name: 'Tajikistan Time', country: 'Tajikistan' },
  { timezone: 'Africa/Dar_es_Salaam', name: 'East Africa Time', country: 'Tanzania, United Republic of' },
  { timezone: 'Asia/Bangkok', name: 'Indochina Time', country: 'Asia/Bangkok' },
  { timezone: 'Asia/Dili', name: 'East Timor Time', country: 'Timor-Leste' },
  { timezone: 'Africa/Lome', name: 'Greenwich Mean Time', country: 'Togo' },
  { timezone: 'Pacific/Fakaofo', name: 'Tokelau Time', country: 'Tokelau' },
  { timezone: 'Pacific/Tongatapu', name: 'Tonga Standard Time', country: 'Tonga' },
  { timezone: 'America/Port_of_Spain', name: 'Atlantic Standard Time', country: 'Trinidad and Tobago' },
  { timezone: 'Africa/Tunis', name: 'Central European Standard Time', country: 'Africa/Tunis' },
  { timezone: 'Europe/Istanbul', name: 'Central European Time', country: 'Turkey' },
  { timezone: 'Asia/Ashgabat', name: 'Turkmenistan Standard Time', country: 'Turkmenistan' },
  { timezone: 'America/Grand_Turk', name: 'Eastern Standard Time', country: 'Turks and Caicos Islands' },
  { timezone: 'Pacific/Funafuti', name: 'Tuvalu Time', country: 'Tuvalu' },
  { timezone: 'Africa/Kampala', name: 'East Africa Time', country: 'Uganda' },
  { timezone: 'Europe/Kiev', name: 'Eastern European Standard Time', country: 'Ukraine' },
  { timezone: 'Europe/Simferopol', name: 'Moscow Standard Time', country: 'Ukraine' },
  { timezone: 'Europe/Uzhgorod', name: 'Eastern European Standard Time', country: 'Ukraine' },
  { timezone: 'Europe/Zaporozhye', name: 'Eastern European Standard Time', country: 'Ukraine' },
  { timezone: 'Asia/Dubai', name: 'Gulf Standard Time', country: 'United Arab Emirates' },
  { timezone: 'Europe/London', name: 'Greenwich Mean Time', country: 'United Kingdom' },
  { timezone: 'America/Adak', name: 'Hawaii-Aleutian Standard Time', country: 'United States' },
  { timezone: 'America/Anchorage', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'America/Boise', name: 'Mountain Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Indianapolis', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Knox', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Marengo', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Petersburg', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Tell_City', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Vevay', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Vincennes', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Indiana/Winamac', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Juneau', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'America/Kentucky/Louisville', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Kentucky/Monticello', name: 'Eastern Standard Time', country: 'United States' },
  { timezone: 'America/Menominee', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/Metlakatla', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'America/Nome', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'America/North_Dakota/Beulah', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/North_Dakota/Center', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/North_Dakota/New_Salem', name: 'Central Standard Time', country: 'United States' },
  { timezone: 'America/Sitka', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'America/Yakutat', name: 'Alaska Standard Time', country: 'United States' },
  { timezone: 'Pacific/Midway', name: 'Samoa Standard Time', country: 'United States Minor Outlying Islands' },
  { timezone: 'Pacific/Wake', name: 'Wake Time', country: 'United States Minor Outlying Islands' },
  { timezone: 'America/Montevideo', name: 'Uruguay Standard Time', country: 'Uruguay' },
  { timezone: 'Asia/Samarkand', name: 'Uzbekistan Time', country: 'Uzbekistan' },
  { timezone: 'Asia/Tashkent', name: 'Uzbekistan Standard Time', country: 'Uzbekistan' },
  { timezone: 'Pacific/Efate', name: 'Vanuatu Standard Time', country: 'Vanuatu' },
  { timezone: 'America/Caracas', name: 'Venezuela Time', country: 'Venezuela, Bolivarian Republic of' },
  { timezone: 'Asia/Ho_Chi_Minh', name: 'Indochina Time', country: 'Viet Nam' },
  { timezone: 'America/Tortola', name: 'Atlantic Standard Time', country: 'Virgin Islands, British' },
  { timezone: 'America/St_Thomas', name: 'Atlantic Standard Time', country: 'Virgin Islands, U.S.' },
  { timezone: 'Pacific/Wallis', name: 'Wallis and Futuna Time', country: 'Wallis and Futuna' },
  { timezone: 'Africa/El_Aaiun', name: 'Western European Summer Time', country: 'Western Sahara' },
  { timezone: 'Asia/Aden', name: 'Arabian Standard Time', country: 'Yemen' },
  { timezone: 'Africa/Lusaka', name: 'Central Africa Time', country: 'Zambia' },
  { timezone: 'Africa/Harare', name: 'Central Africa Time', country: 'Zimbabwe' },
  { timezone: 'Europe/Mariehamn', name: 'Eastern European Standard Time', country: 'Åland Islands' },
];

// TODO: add UTC and LOCAL
export const getTimezoneData = (timezone) => {
  return TIMEZONE_LIST.find((item) => item.timezone === timezone);
};

export const getCurrencyFromTimezone = (timezone) => {
  const timezoneData = getTimezoneData(timezone);
  const country = timezoneData?.country;

  if (!country) return 'GBP';

  const EUR_COUNTRIES = ['Austria', 'Belgium', 'Cyprus', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Portugal', 'Slovakia', 'Slovenia', 'Spain'];
  const USD_COUNTRIES = ['United States', 'Ecuador', 'El Salvador', 'Guam', 'Northern Mariana Islands', 'Puerto Rico', 'American Samoa', 'U.S. Virgin Islands', 'East Timor', 'Palau', 'Micronesia', 'Marshall Islands'];

  if (EUR_COUNTRIES.includes(country)) return 'EUR';
  if (USD_COUNTRIES.includes(country)) return 'USD';
  return 'GBP';
};